export const FETCH_LIBRARY = "FETCH_LIBRARY";
export const FETCH_LIBRARY_SUCCESS = "FETCH_LIBRARY_SUCCESS";
export const FETCH_LIBRARY_ERROR = "FETCH_LIBRARY_ERROR";
export const RENDER_LIBRARY = "RENDER_LIBRARY";
export const SELECT_DOCUMENT = "SELECT_DOCUMENT";
export const SET_VISIBILITY = "SET_VISIBILITY";
